version: "3"

services:
  database:
    image: "postgres:latest"
    env_file:
        - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/